### ISSUE TITLE
Mpv.js example cannot run in version 5.0.3 of electron

### ISSUE THREAD

**Issue by wuwei2150** [Kagami/mpv.js#52] opened 2019-06-26 08:12 UTC
Mpv.js example cannot run in version 5.0.3 of electron
![image](https://user-images.githubusercontent.com/12472829/60162929-1d0f4100-982d-11e9-8c2e-4b6e9f0dfb6b.png)

**Comment by Kagami** [comment] 2019-06-26 08:34
Should be duplicate of #51. Need investigation.

**Closed as completed by Kagami** 2019-06-26 08:34 UTC
