### ISSUE TITLE
OpenGL error in electron 2.0.0

### ISSUE THREAD

**Issue by itshaadi** [Kagami/mpv.js#25] opened 2018-05-03 12:42 UTC
electron 2.0.0 was released yesterday and I tried it with mpv.js. everything looks fine but I get this Error message in my console. it doesn't seems to be affecting the player functionality but nevertheless it's an error.

os: windows 10_x64 build 16299
electron: 2.0.0

```
[11664:0503/170106.364:ERROR:texture_manager.cc(2437)] [.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexImage2D: invalid internal_format GL_RGBA16_EXT
[opengl-cb] after creating texture: OpenGL error INVALID_VALUE.
[opengl-cb] Error: framebuffer completeness check failed (error=36054).
[opengl-cb] Error: texture could not be created.
```

**Comment by xaiki** [comment] 2018-06-06 17:26
getting the same error, but can't make mpv.js do anything on electron 2.0.2, the example doesn't work if updated.

**Comment by EdwardLiao** [comment] 2018-07-05 18:10
Found the same error on electron 2.0.3, mpv.js displays "Couldn't load plugin" in the container window.

**Comment by Kagami** [comment] 2018-07-21 14:10
Can reproduce it. Probably Chrome broken something in PPAPI implementation.

**Comment by Kagami** [comment] 2018-07-21 14:27
Though plugins seems to be working normally in latest Chromium.
Might be something electron-related.

**Comment by Kagami** [comment] 2018-07-21 14:50
Tested a bit more.

* Works fine with electron 1.x
* Shows error for electron 2.0.x
* Works fine with electron 3.0.0-beta.x

Seems to be either regression in Electron or Chrome 61. Does anyone know for how long electron 2.x is going to be supported? I.e. is it worth the efforts.

**Comment by Kagami** [comment] 2018-07-21 14:59
Might be related https://github.com/electron/electron/issues/12937

**Comment by Kagami** [comment] 2018-07-21 15:49
Tested Chrome 61÷66, issue seems to be fixed somewhere between 64 and 65.

**Comment by Kagami** [comment] 2018-07-21 16:27
Found commit which fixes error: https://chromium.googlesource.com/chromium/src.git/+/37924baf9ac8f3ce7811508bc650efe965bb50b2^!/

**Comment by Kagami** [comment] 2018-07-22 01:03
Closing because it was fixed in latest electron/Chrome (3+/65+) and doesn't affect functionality.
As far as I can understand it happens because Chrome reports support for 16bit textures, mpv tries to create 16bit FBO and that fails, so it fallbacks to usual dumb mode.

There is one more issue which I thought was related to this one, but it seems to be happen only on Linux: electron/electron#13624

**Closed as completed by Kagami** 2018-07-22 01:03 UTC

**Comment by itshaadi** [comment] 2018-08-12 13:35
on 2.0.x ARM releases for raspberry pi you can fix this issue by [enabling hardware graphics acceleration](https://github.com/Kagami/mpv.js#step-0-enable-hardware-graphics-acceleration).
